apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: hms-prod
data:
  PORT: "5001"
  SERVICE_NAME: "user-service"
  MONGO_URI: "mongodb://admin:admin123@mongodb:27017/?authSource=admin"
  AUTH_SERVICE_URL: "http://auth-service:5000"
  USER_SERVICE_URL: "http://user-service:5001"
  APPOINTMENT_SERVICE_URL: "http://appointment-service:5002"
  NOTIFICATION_SERVICE_URL: "http://notification-service:5004"
  API_GATEWAY_URL: "http://api-gateway:4000"
