apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
  namespace: hms-prod
type: Opaque
stringData:
  JWT_SECRET: "prod_super_secure_jwt_secret_123"
  INTERNAL_API_KEY: "prod_internal_key"
